name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.21
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build Go app
      run: go build -o go-web-app

    - name: Run tests
      run: go test ./...

  docker-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}

  update-helm-tag:
    runs-on: ubuntu-latest
    needs: docker-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}  # Your GitHub PAT

    - name: Update image tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push updated Helm chart
      run: |
        git config --global user.email "susangod6@gmail.com"
        git config --global user.name "Susan-creator"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update image tag to ${{ github.run_id }}"
        git push
